### ISSUE TITLE
Access denied for user 'kimaiuser'@'172.19.0.3' (using password: YES)

### ISSUE THREAD

**Issue by Mebus** [tobybatch/kimai2#161]
Hallo,

I have tried to use the docker-compose.yml file to build a production setup, but I get the following error:

`sqldb_1    | 2020-09-30T11:02:28.999113Z 5 [Note] Access denied for user 'kimaiuser'@'172.19.0.3' (using password: YES)
`

Why is this happening?

Mebus

**Comment by tobybatch** [comment]
Please open a ticket with the details of your set up.  I can't help you because I can't see any of your settings.  It looks like you're using the composer set up but I need more.

**Comment by Mebus** [comment]
Thanks for closing the ticket instantly...

I didn't use any settings. Just ran `docker-compose up`.

Mebus

**Comment by bt35** [comment]
Hey All! I spent a good bit of time dealing with the error that Mebus saw.

Below in the list is what happened and also what I think also happened for Mebus. Though I am making an assumption that Mebus had the same exact problem I did. Assumptions you know? Apologies if I assumed wrongly and please pay close attention to the sentence marked with [*] if I did assume wrongly. 

1. I did several docker-compose up commands. Several times like 5 to 10.
2. I modified the passwords in the docker-compose.yml thinking that was changing the passwords. It was not. See answer number 3 in this stack overflow [1].
3. So the original passwords I sent in the very first docker-compose.yml edit I did were the passwords that were set on the database. 

How did I fix? I deleted the volumes with the command below. Reference: [2]

```
docker-compose down--volumes 
```

[*] Do not run the above command unless fully prepared to lose the data contained in the volumes. I was OK with deleting the volumes since I could not even use the application. 

Another way to fix this would be to change the docker-config.yml back to the original passwords if I had written them down. I did not which was a mistake. 

[1] https://stackoverflow.com/questions/40149880/docker-mysql-root-password-do-not-work/64442155
[2] https://docs.docker.com/compose/reference/down/

**Comment by tobybatch** [comment]
The mysql image isn't anything to do with the kimai image, we just use it to store data.

Can you run the mysql command stand alone and have it connect, e.g. 

    docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:tag

 1. Which docker-compose file are you you using? I can't see attached.
 2. Which passwords? I can see and examples of where the passwords are listed
 3. Which docker-compose.yml. I can't see one attached.

 I can't help you because I can't see any of your settings. Try opening a new ticket with the bug template filled out: https://github.com/tobybatch/kimai2/issues/new?assignees=&labels=&template=bug_report.md&title=%5BBUG%5D+

**Comment by bt35** [comment]
Thanks for writing back. In short you need do nothing. 

All I was trying to do was help others not make the same mistake I did. I used the same compose file as is in the github repo but modified the passwords, poorly. 

More precisely, I set the mysql image kimaiuser password to "X" and did not set that password in the Kimai section of the compose file. Then I made things worse by changing the mysql password to "Y" and then setting the kimai password to "Y". Therefore on upstart PHP would report access denied 1045. I got into this mess because I did not write down the first password and also because I did not fully understand what docker-compose was doing. 

Once the password were set to "Z" for kimaiuser in both mysql and kimai sections I was able to access kimai. It works, I have created a user accessed the application and all is well. 

Thanks.
