### ISSUE TITLE
Can not start docker-compose setup with dev image

### ISSUE THREAD

**Issue by schmunk42** [tobybatch/kimai2#18]
Switched image to

    image: kimai/kimai2:dev

Got the following error:

    Unsupported database engine: . Kimai only supports one of: mysql, sqlite

**Comment by schmunk42** [comment]
After digging in the code, I think maybe I understood `prod` and `dev` wrong, since the `prod` image is built upon `dev`.

What I am actually looking after is running the same version as https://demo.kimai.org/de/login "Development version"

CC: @kevinpapst

**Comment by kevinpapst** [comment]
Can't help with docker, sorry. But this might help:
https://www.kimai.org/documentation/installation.html#development-installation

**Comment by schmunk42** [comment]
Which version or commit-sha is running on the URL above, `master` latest green build?

**Comment by tobybatch** [comment]
I think all the DB issues are due to how the DATABASE_URL is set.  The dev image only supports the sqlite DB at the moment.

@schmunk42 If you want to use mysql with the dev image then you will need ste a env varible for DATABASE_URL and mount a custom .env file that points to your mysql instance.  Can I see your docker-compose.yml please?

**Comment by schmunk42** [comment]
I used the `docker-compose.yml` from this repo. 

After reading the `Dockerfile`s I understood, that this is related to the startup scripts. I was just confused that `prod` is built upon `dev`.

This issue is resolved for me.
