### ISSUE TITLE
LDAP CONF

### ISSUE THREAD

**Issue by SoufianBakhti** [tobybatch/kimai2#192]
Hi guys,

i'v just build kimai2 with docker-compose 
everything is Ok

i just need your helps, i'am not an expert, i want configure LDAP authentification.

can someone gives me the step to use ldap please ?!

thanks a lot

**Comment by SoufianBakhti** [comment]
@tobybatch any advice please !

**Comment by tobybatch** [comment]
OK, so this is an issue with the kimai config.  You need to look here: https://www.kimai.org/documentation/ldap.html

Also to rule out issues with the config for your set up could re-open the issue here with your details please: https://github.com/tobybatch/kimai2/issues/new?assignees=&labels=&template=bug_report.md&title=%5BBUG%5D+

Without those details I can't debug what you are doing wrong.
