### ISSUE TITLE
[BUG] Call to undefined function cal_days_in_month() reloaded

### ISSUE THREAD

**Issue by dhoernel** [tobybatch/kimai2#499]
Describe the bug (also see discussion of #317):
We have installed the newest version of the Controlling Plugin. This Plugin uses the php function cal_days_in_month().

Steps to reproduce the behaviour:
Start the container
Execute a shell within the container
Within the shell run php -a
Run echo cal_days_in_month(CAL_GREGORIAN, 8, 2003);
The result is the following error message:
PHP Warning:  Uncaught Error: Call to undefined function cal_days_in_month() in php shell code:1
Stack trace:
#0 {main}
  thrown in php shell code on line 1

Desktop (please complete the following information):
OS: Rocky Linux 9.1
Docker version: 23.0.1
Docker compose version: 2.16.0

Command used to run the container:
docker start kimai-kimai-1

Kimai version 1.30.11
Controlling plugin version 1.23

Is there any step by step guide to resolve it or (better) a Docker image that fixes the problem?

**Comment by kevinpapst** [comment]
We already decided that this will not be fixed in this repository.

I added a statement how the author of your plugin can fix it with a simple copy & paste of three lines of code:
https://github.com/tobybatch/kimai2/issues/317#issuecomment-987756506

I wrote the author of the paid plugin in December 2021 about that issue. 
If they decided to ignore it, you can remind them again. No ... you SHOULD write them. 
All the arguments were already given in the other issue.

It is not the community that needs to fix an issue of the author of a paid plugin.
