### ISSUE TITLE
Custom field in timesheet

### ISSUE THREAD

**Issue by SpoorthiPalakshaiah** [tobybatch/kimai2#90]
I used the official document https://www.kimai.org/documentation/meta-fields.html to add custom fields.. It was working in development docker with image kimai/kimai2:dev But the same is not working in production docker with image kimai/kimai2:apache-debian-master-prod

**Comment by tobybatch** [comment]
# Can you give a clear view of the evn you are using please?

**Describe the bug**

A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the container '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Docker version: [e.g. 19.03.2]
 - Docker compose version: [e.g. 1.21.0]

**Command used to run the container**
 - [e.g. docker run -v ....]

**Docker compose file (with passwords redacted)**

```yaml
version: '3.5'
services:
   image: ...
```

**Additional context**
Add any other context about the problem here.

**Comment by SpoorthiPalakshaiah** [comment]
Desktop:
-> OS: iOS 10.14.6
-> Docker version: 19.03.5
-> Docker compose version: 1.25.4

Command used to run the container:
docker run -itd -p 8001:8001 --name kimai kimai/kimai2:apache-debian-master-prod

Question:
To add custom fields, Should I have files as MetaFieldSubscriber.php and MetaFieldDisplaySubscriber.php in /opt/kimai/src/EventSubscriber with contents as in documentation https://www.kimai.org/documentation/meta-fields.html

Issue:
I'm unable to add custom fields in timesheet by following above steps.
